#!/bin/bash
# @author chance@chancegarcia.com

if [ ! -e /usr/bin/lsb_release ]; then
    echo "unable to find lsb_release to check for ubuntu system. only use this on ubuntu"
    exit 1
fi

if [ ! $# -eq 1 ]; then
    echo "please specify a php version to swtich to"
    exit 1
else
    if [[ $1 =~ [0-9]\.[0-9]+? ]]; then
        switch_to=$1
    else
        echo "invalid paramenter"
        exit 1
    fi
fi

echo "switch to PHP $switch_to"

switch_from=`php --version | grep -oP "PHP (\d\.\d+?)" | cut -d " " -f2`
echo "switch from PHP $switch_from"
echo "this will require sudo priveleges"

echo "switching CLI"
sudo update-alternatives --set php /usr/bin/php$switch_to

echo "switching apache"
sudo a2dismod php$switch_from;
sudo a2enmod php$switch_to;
sudo service apache2 restart
