#!/bin/bash
# creator: Chance Garcia <chance@chancegarcia.com>
# twitter: chancegarcia

if [ ! -e /usr/bin/lsb_release ]; then
    echo "unable to find lsb_release to check for ubuntu system. only use this on ubuntu"
    exit 1
fi

# todo use/parse lsb_release to verify ubuntu

if [ ! $# -eq 1 ]; then
    echo "please specify a php version to swtich to"
    echo "valid choices are:"
    update-alternatives --list php | grep -oP "(\d\.\d+?)"
    exit 1
else
    if [[ $1 =~ [0-9]\.[0-9]+? ]]; then
        switch_to=$1
    else
        echo "invalid version number"
        exit 1
    fi
fi

echo "switch to PHP $switch_to"

switch_from=`php --version | grep -oP "PHP (\d\.\d+?)" | cut -d " " -f2`
echo "switch from PHP $switch_from"
echo "this will require sudo privileges"

echo "switching CLI"
sudo update-alternatives --set php /usr/bin/php$switch_to
# todo add phar, etc?

echo "switching apache"
sudo a2dismod php$switch_from;
sudo a2enmod php$switch_to;

read -p "activate new config 'sudo systemctl restart apache2' (y/N)?" yn
case $yn in
        [Yy]* ) sudo systemctl restart apache2; break;;
        [Nn]* ) exit;;
        * ) echo exit;;
    esac

echo "php switch to $switch_to is now complete"
php --version

